---
- name: Pull the latest stable collabora code image
  community.docker.docker_image_pull:
    name: collabora/code
    tag: latest
    pull: always
  become: true

- name: Ensure the docker network exists if defined
  community.docker.docker_network:
    name: "{{ collabora_code_docker_network }}"
    driver: "bridge"
  when: collabora_code_docker_network is defined

- name: Ensure the collabora code container is running
  community.docker.docker_container:
    name: collabora-code
    image: collabora/code:latest
    state: started
    hostname: collabora-code
    auto_remove: false
    restart_policy: unless-stopped
    cpus: "{{ collabora_code_cpus }}"
    memory: "{{ collabora_code_memory }}"
    memory_swap: "{{ collabora_code_memory }}"
    network_mode: "{{ collabora_code_docker_network | default('bridge') }}"
    detach: true
    published_ports: "{{ collabora_code_ports | default(omit) }}"
    env: "{{ collabora_code_env_vars }}"
    capabilities:
    - SYS_CHROOT
    - SYS_ADMIN
    - FOWNER
    - CHOWN
    cap_drop:
    - all
    log_driver: json-file
    log_options:
      max-size: 50m
      max-file: "3"
  become: true

- name: Check if avahi-daemon is running
  ansible.builtin.set_fact:
    avahi_daemon_running: "{{ ansible_facts.services['avahi-daemon.service'] is defined and ansible_facts.services['avahi-daemon.service'].state == 'running' }}"
  when: collabora_code_avahi_publish is defined and collabora_code_avahi_publish

- name: Ensure the collabora code avahi-publish systemd service is created
  ansible.builtin.template:
    src: systemd-avahi-publish.service.j2
    dest: "/etc/systemd/system/avahi-publish-collabora-code.service"
    mode: 0644
    owner: root
  become: true
  register: collabora_code_avahi_publish_service
  when: collabora_code_avahi_publish is defined and collabora_code_avahi_publish and avahi_daemon_running

- name: Ensure the collabora code avahi-publish systemd service is enabled and started
  ansible.builtin.systemd_service:
    name: avahi-publish-collabora-code.service
    state: "{{ 'restarted' if collabora_code_avahi_publish_service.changed else 'started' }}"
    enabled: yes
    daemon_reload: "{{ collabora_code_avahi_publish_service.changed }}"
  become: true
  when: collabora_code_avahi_publish is defined and collabora_code_avahi_publish and avahi_daemon_running
