---
- name: Pull the latest ntfy image
  community.docker.docker_image_pull:
    name: binwiederhier/ntfy
    tag: latest
    pull: always
  become: true

- name: Ensure the cache ntfy directory is present
  ansible.builtin.file:
    path: "/home/{{ ansible_facts.user_id }}/ansible-roles-debian-data/ntfy/cache"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    mode: 0755
  become: true

- name: Ensure the docker network exists if defined
  community.docker.docker_network:
    name: "{{ ntfy_docker_network }}"
    driver: "bridge"
  when: ntfy_docker_network is defined

- name: Ensure the ntfy container is running
  community.docker.docker_container:
    name: ntfy
    image: binwiederhier/ntfy:latest
    state: started
    hostname: ntfy
    auto_remove: false
    restart_policy: unless-stopped
    cpus: "{{ ntfy_cpus }}"
    memory: "{{ ntfy_memory }}"
    memory_swap: "{{ ntfy_memory }}"
    detach: true
    network_mode: "{{ ntfy_docker_network | default('bridge') }}"
    published_ports: "{{ ntfy_ports | default(omit) }}"
    command: "serve --cache-file /var/cache/ntfy/cache.db"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:8090/v1/health -O - | grep -Eo '\"healthy\":true' > /dev/null || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
    - "/home/{{ ansible_facts.user_id }}/ansible-roles-debian-data/ntfy/cache:/var/cache/ntfy:rw"
    env: "{{ ntfy_env_vars }}"
    log_driver: json-file
    log_options:
      max-size: 50m
      max-file: "3"
  become: true

- name: Check if avahi-daemon is running
  ansible.builtin.set_fact:
    avahi_daemon_running: "{{ ansible_facts.services['avahi-daemon.service'] is defined and ansible_facts.services['avahi-daemon.service'].state == 'running' }}"
  when: adguard_avahi_publish is defined and adguard_avahi_publish

- name: Ensure the ntfy avahi-publish systemd service is created
  ansible.builtin.template:
    src: systemd-avahi-publish.service.j2
    dest: "/etc/systemd/system/avahi-publish-ntfy.service"
    mode: 0644
    owner: root
  become: true
  register: ntfy_avahi_publish_service
  when: ntfy_avahi_publish is defined and ntfy_avahi_publish and avahi_daemon_running

- name: Ensure the ntfy avahi-publish systemd service is enabled and started
  ansible.builtin.systemd_service:
    name: avahi-publish-ntfy.service
    state: "{{ 'restarted' if ntfy_avahi_publish_service.changed else 'started' }}"
    enabled: yes
    daemon_reload: "{{ ntfy_avahi_publish_service.changed }}"
  become: true
  when: ntfy_avahi_publish is defined and  ntfy_avahi_publish and avahi_daemon_running
